apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: mediawiki